before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/scone/
    binary: "{{ .ProjectName }}"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch: # 64-bit only
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
    rlcp: true
checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^refactor:'
      - '^test:'
      - '^chore:'
      - '^build:'

brews:
  - repository:
      owner: haijima
      name: homebrew-tap
      token: "{{ .Env.PAT_FOR_HOMEBREW_TAP }}"
    folder: Formula
    description: "Analyzes SQL queries"
    homepage: "{{ .GitURL }}"
    license: "MIT"
